### PR TITLE
index samples by sample name for easier access.

### PR DESCRIPTION
**Pull request by brentp**

### CODE REVIEW

**Comment by brentp** [comment]
SHA: c1af7f59edf25be5b78e570890a7e9523d6cf460

should be a separate pull request, but I can't see how to do that. It adds a genotypes() method so that one can get the un-encoded genotypes from the encoded ones.
This might work better if Record were a class rather than a named tuple, then we could add methods to record.

**Comment by jamescasbon** [comment]
A good case for an OrderedDict so that we can access by name, but iterating the values provides the order as in the file?
http://docs.python.org/dev/library/collections.html#collections.OrderedDict

**Comment by brentp** [comment]
Seems reasonable, especially since it's usually going to be a fairly small dictionary. I'll add this to the pull request later today.

**Comment by brentp** [comment]
although OrderedDicts are not in python2.6 collections

**Comment by jamescasbon** [comment]
Always with your backwards compatibility!  Oh well, it was a nice to have, but version for 2.6 listed here: 
http://stackoverflow.com/questions/1617078/ordereddict-for-older-versions-of-python

not sure its worth a dependency.

**Comment by jamescasbon** [comment]
Please continue issue at https://github.com/jamescasbon/PyVCF/issues/1

**Comment by jamescasbon** [comment]
A quick note since everyone is watching this issue.  

I have fixed this on my fork using OrderedDict from collections.  If python<2.7 setup.py should install some code to do that.

**Pull request closed without merging**
